[pytest]
markers =
    ui: UI-тесты
    api: API-тесты
    positive: позитивные тесты
    negative: негативные тесты
    chrome: тесты для Chrome
    edge: тесты для Edge
    firefox: тесты для Firefox